### ISSUE TITLE
Show leaderboard

### ISSUE THREAD

**Issue by thisIsTheFoxe** [SwiftPackageRepository/GameKitUI.swift#17]
Is it possible to show the leaderboard aka the general `GKGameCenterViewController` using SwiftUI?

**Comment by smuellner** [comment]
Hi @thisIsTheFoxe 

This should not be a problem and even quite simple as it is available on iOS, macOS and tvOS.
If you like you can add a PR for it and I would be happy to I integrate it.

￼thank you very much for using the library

**Comment by thisIsTheFoxe** [comment]
Great, will do... It just might take a bit for me to find the time .-.
