### ISSUE TITLE
Extra comments don't match Licence

### ISSUE THREAD

**Issue by Henac** [SwiftPackageRepository/GameKitUI.swift#2]
Hi @smuellner 

Thanks for developing this great package!I was hoping to use your GameKitUI in my app and looking at the Licence it seems that I can, but there are some comments in the code that possibly contradict the MIT Licence. Would it be possible to remove the contradictory statements or possibly clarify what unauthorised usage is?

Thanks
 

https://github.com/SwiftPackageRepository/GameKitUI.swift/blob/8abe470803099719992505eb4d1e782ca30a5724/Sources/GameKitUI/GKMatchMakerView.swift#L6

**Comment by smuellner** [comment]
Thank you for the report. 
Definitely the license in the extra header was inconsistent and is now replaced with the MIT license. 
I am very happy that you plan to use GameKitUI in your application and really welcome your feedback. <3

**Comment by Henac** [comment]
Thanks so much for the quick turnaround on these couple of bugs, it is very much appreciated. This library makes using the Game Center so much more Swifty!
