### ISSUE TITLE
How to accept invitations?

### ISSUE THREAD

**Issue by cpytel** [SwiftPackageRepository/GameKitUI.swift#7]
Hi, thanks for this library. I'm attempting to accept an invitation from another player and having trouble figuring out how to do that. The other player successfully gets the push notification, taps it, and the app launches, but then nothing happens.

I'm sure I need to do something in the app to see the invitation and accept it, but I'm not sure what that is. Any help would be appreciated. Thanks!

**Comment by smuellner** [comment]
Hello,

thanks a lot for trying out the project. There seems to be an issue with the authentication process and I will try to fix this the upcoming week. I would be very happy if you can look over the changes and verify they are working.

Thanks so much for your support,
Sascha

**Comment by smuellner** [comment]
Hello,

If you have time and like to verify, if the changes help you with the authentication and match making are now working as expected on this PR

https://github.com/SwiftPackageRepository/GameKitUI.swift/pull/9

Remark: Documentation and the according changes for the turn based Match are missing.

Best regards,
Sascha

**Comment by smuellner** [comment]
@cpytel Hello,

I extended the example and added more documentation on accepting an invite. It would be nice if you can verify the new changes are working for you as expected.

Kind regards,
Sascha
